export const types = Object.freeze({
    // Async
    FETCH_TASKS_ASYNC: 'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC: 'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC: 'REMOVE_TASK_ASYNC',
    UPDATE_TASK_ASYNC: 'UPDATE_TASK_ASYNC',
    COMPLETE_TASKS_ASYNC: 'COMPLETE_TASKS_ASYNC',
    // Sync
    FILL_TASKS: 'FILL_TASKS',
    CREATE_TASK: 'CREATE_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    COMPLETE_TASKS: 'COMPLETE_TASKS',
});
